/*
 * This file is part of the coreboot project.
 *
 * Copyright 2015 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 */

#ifndef SOC_MEDIATEK_MT8173_SPM_H
#define SOC_MEDIATEK_MT8173_SPM_H

#include <soc/addressmap.h>
#include <types.h>

/**************************************
 * Define and Declare
 **************************************/
enum {
	SPM_POWERON_CONFIG_SET		= SPM_BASE + 0x000,
	SPM_POWER_ON_VAL0		= SPM_BASE + 0x010,
	SPM_POWER_ON_VAL1		= SPM_BASE + 0x014,
	SPM_CLK_SETTLE			= SPM_BASE + 0x100,
	SPM_CA7_CPU0_PWR_CON		= SPM_BASE + 0x200,
	SPM_CA7_DBG_PWR_CON		= SPM_BASE + 0x204,
	SPM_CA7_CPUTOP_PWR_CON		= SPM_BASE + 0x208,
	SPM_VDE_PWR_CON			= SPM_BASE + 0x210,
	SPM_MFG_PWR_CON			= SPM_BASE + 0x214,
	SPM_CA7_CPU1_PWR_CON		= SPM_BASE + 0x218,
	SPM_CA7_CPU2_PWR_CON		= SPM_BASE + 0x21c,
	SPM_CA7_CPU3_PWR_CON		= SPM_BASE + 0x220,
	SPM_VEN_PWR_CON			= SPM_BASE + 0x230,
	SPM_IFR_PWR_CON			= SPM_BASE + 0x234,
	SPM_ISP_PWR_CON			= SPM_BASE + 0x238,
	SPM_DIS_PWR_CON			= SPM_BASE + 0x23c,
	SPM_DPY_PWR_CON			= SPM_BASE + 0x240,
	SPM_CA7_CPUTOP_L2_PDN		= SPM_BASE + 0x244,
	SPM_CA7_CPUTOP_L2_SLEEP		= SPM_BASE + 0x248,
	SPM_CA7_CPU0_L1_PDN		= SPM_BASE + 0x25c,
	SPM_CA7_CPU1_L1_PDN		= SPM_BASE + 0x264,
	SPM_CA7_CPU2_L1_PDN		= SPM_BASE + 0x26c,
	SPM_CA7_CPU3_L1_PDN		= SPM_BASE + 0x274,
	SPM_GCPU_SRAM_CON		= SPM_BASE + 0x27c,
	SPM_DPY2_PWR_CON		= SPM_BASE + 0x280,
	SPM_MD_PWR_CON			= SPM_BASE + 0x284,
	SPM_MCU_PWR_CON			= SPM_BASE + 0x290,
	SPM_IFR_SRAMROM_CON		= SPM_BASE + 0x294,
	SPM_MJC_PWR_CON			= SPM_BASE + 0x298,
	SPM_AUDIO_PWR_CON		= SPM_BASE + 0x29c,
	SPM_CA15_CPU0_PWR_CON		= SPM_BASE + 0x2a0,
	SPM_CA15_CPU1_PWR_CON		= SPM_BASE + 0x2a4,
	SPM_CA15_CPU2_PWR_CON		= SPM_BASE + 0x2a8,
	SPM_CA15_CPU3_PWR_CON		= SPM_BASE + 0x2ac,
	SPM_CA15_CPUTOP_PWR_CON		= SPM_BASE + 0x2b0,
	SPM_CA15_L1_PWR_CON		= SPM_BASE + 0x2b4,
	SPM_CA15_L2_PWR_CON		= SPM_BASE + 0x2b8,
	SPM_MFG_2D_PWR_CON		= SPM_BASE + 0x2c0,
	SPM_MFG_ASYNC_PWR_CON		= SPM_BASE + 0x2c4,
	SPM_VPU_SRAM_CON		= SPM_BASE + 0x2c8,
	SPM_PCM_CON0			= SPM_BASE + 0x310,
	SPM_PCM_CON1			= SPM_BASE + 0x314,
	SPM_PCM_IM_PTR			= SPM_BASE + 0x318,
	SPM_PCM_IM_LEN			= SPM_BASE + 0x31c,
	SPM_PCM_REG_DATA_INI		= SPM_BASE + 0x320,
	SPM_PCM_EVENT_VECTOR0		= SPM_BASE + 0x340,
	SPM_PCM_EVENT_VECTOR1		= SPM_BASE + 0x344,
	SPM_PCM_EVENT_VECTOR2		= SPM_BASE + 0x348,
	SPM_PCM_EVENT_VECTOR3		= SPM_BASE + 0x34c,
	SPM_PCM_MAS_PAUSE_MASK		= SPM_BASE + 0x354,
	SPM_PCM_PWR_IO_EN		= SPM_BASE + 0x358,
	SPM_PCM_TIMER_VAL		= SPM_BASE + 0x35c,
	SPM_PCM_TIMER_OUT		= SPM_BASE + 0x360,
	SPM_PCM_REG0_DATA		= SPM_BASE + 0x380,
	SPM_PCM_REG1_DATA		= SPM_BASE + 0x384,
	SPM_PCM_REG2_DATA		= SPM_BASE + 0x388,
	SPM_PCM_REG3_DATA		= SPM_BASE + 0x38c,
	SPM_PCM_REG4_DATA		= SPM_BASE + 0x390,
	SPM_PCM_REG5_DATA		= SPM_BASE + 0x394,
	SPM_PCM_REG6_DATA		= SPM_BASE + 0x398,
	SPM_PCM_REG7_DATA		= SPM_BASE + 0x39c,
	SPM_PCM_REG8_DATA		= SPM_BASE + 0x3a0,
	SPM_PCM_REG9_DATA		= SPM_BASE + 0x3a4,
	SPM_PCM_REG10_DATA		= SPM_BASE + 0x3a8,
	SPM_PCM_REG11_DATA		= SPM_BASE + 0x3ac,
	SPM_PCM_REG12_DATA		= SPM_BASE + 0x3b0,
	SPM_PCM_REG13_DATA		= SPM_BASE + 0x3b4,
	SPM_PCM_REG14_DATA		= SPM_BASE + 0x3b8,
	SPM_PCM_REG15_DATA		= SPM_BASE + 0x3bc,
	SPM_PCM_EVENT_REG_STA		= SPM_BASE + 0x3c0,
	SPM_PCM_FSM_STA			= SPM_BASE + 0x3c4,
	SPM_PCM_IM_HOST_RW_PTR		= SPM_BASE + 0x3c8,
	SPM_PCM_IM_HOST_RW_DAT		= SPM_BASE + 0x3cc,
	SPM_PCM_EVENT_VECTOR4		= SPM_BASE + 0x3d0,
	SPM_PCM_EVENT_VECTOR5		= SPM_BASE + 0x3d4,
	SPM_PCM_EVENT_VECTOR6		= SPM_BASE + 0x3d8,
	SPM_PCM_EVENT_VECTOR7		= SPM_BASE + 0x3dc,
	SPM_PCM_SW_INT_SET		= SPM_BASE + 0x3e0,
	SPM_PCM_SW_INT_CLEAR		= SPM_BASE + 0x3e4,
	SPM_CLK_CON			= SPM_BASE + 0x400,
	SPM_SLEEP_DUAL_VCORE_PWR_CON	= SPM_BASE + 0x404,
	SPM_SLEEP_PTPOD2_CON		= SPM_BASE + 0x408,
	SPM_APMCU_PWRCTL		= SPM_BASE + 0x600,
	SPM_AP_DVFS_CON_SET		= SPM_BASE + 0x604,
	SPM_AP_STANBY_CON		= SPM_BASE + 0x608,
	SPM_PWR_STATUS			= SPM_BASE + 0x60c,
	SPM_PWR_STATUS_2ND		= SPM_BASE + 0x610,
	SPM_AP_BSI_REQ			= SPM_BASE + 0x614,
	SPM_SLEEP_TIMER_STA		= SPM_BASE + 0x720,
	SPM_SLEEP_TWAM_CON		= SPM_BASE + 0x760,
	SPM_SLEEP_TWAM_STATUS0		= SPM_BASE + 0x764,
	SPM_SLEEP_TWAM_STATUS1		= SPM_BASE + 0x768,
	SPM_SLEEP_TWAM_STATUS2		= SPM_BASE + 0x76c,
	SPM_SLEEP_TWAM_STATUS3		= SPM_BASE + 0x770,
	SPM_SLEEP_WAKEUP_EVENT_MASK	= SPM_BASE + 0x810,
	SPM_SLEEP_CPU_WAKEUP_EVENT	= SPM_BASE + 0x814,
	SPM_SLEEP_MD32_WAKEUP_EVENT_MASK	= SPM_BASE + 0x818,
	SPM_PCM_WDT_TIMER_VAL		= SPM_BASE + 0x824,
	SPM_PCM_WDT_TIMER_OUT		= SPM_BASE + 0x828,
	SPM_PCM_MD32_MAILBOX		= SPM_BASE + 0x830,
	SPM_PCM_MD32_IRQ		= SPM_BASE + 0x834,
	SPM_SLEEP_ISR_MASK		= SPM_BASE + 0x900,
	SPM_SLEEP_ISR_STATUS		= SPM_BASE + 0x904,
	SPM_SLEEP_ISR_RAW_STA		= SPM_BASE + 0x910,
	SPM_SLEEP_MD32_ISR_RAW_STA	= SPM_BASE + 0x914,
	SPM_SLEEP_WAKEUP_MISC		= SPM_BASE + 0x918,
	SPM_SLEEP_BUS_PROTECT_RDY	= SPM_BASE + 0x91c,
	SPM_SLEEP_SUBSYS_IDLE_STA	= SPM_BASE + 0x920,
	SPM_PCM_RESERVE			= SPM_BASE + 0xb00,
	SPM_PCM_RESERVE2		= SPM_BASE + 0xb04,
	SPM_PCM_FLAGS			= SPM_BASE + 0xb08,
	SPM_PCM_SRC_REQ			= SPM_BASE + 0xb0c,
	SPM_PCM_DEBUG_CON		= SPM_BASE + 0xb20,
	SPM_CA7_CPU0_IRQ_MASK		= SPM_BASE + 0xb30,
	SPM_CA7_CPU1_IRQ_MASK		= SPM_BASE + 0xb34,
	SPM_CA7_CPU2_IRQ_MASK		= SPM_BASE + 0xb38,
	SPM_CA7_CPU3_IRQ_MASK		= SPM_BASE + 0xb3c,
	SPM_CA15_CPU0_IRQ_MASK		= SPM_BASE + 0xb40,
	SPM_CA15_CPU1_IRQ_MASK		= SPM_BASE + 0xb44,
	SPM_CA15_CPU2_IRQ_MASK		= SPM_BASE + 0xb48,
	SPM_CA15_CPU3_IRQ_MASK		= SPM_BASE + 0xb4c,
	SPM_PCM_PASR_DPD_0		= SPM_BASE + 0xb60,
	SPM_PCM_PASR_DPD_1		= SPM_BASE + 0xb64,
	SPM_PCM_PASR_DPD_2		= SPM_BASE + 0xb68,
	SPM_PCM_PASR_DPD_3		= SPM_BASE + 0xb6c,
	SPM_SLEEP_CA7_WFI0_EN		= SPM_BASE + 0xf00,
	SPM_SLEEP_CA7_WFI1_EN		= SPM_BASE + 0xf04,
	SPM_SLEEP_CA7_WFI2_EN		= SPM_BASE + 0xf08,
	SPM_SLEEP_CA7_WFI3_EN		= SPM_BASE + 0xf0c,
	SPM_SLEEP_CA15_WFI0_EN		= SPM_BASE + 0xf10,
	SPM_SLEEP_CA15_WFI1_EN		= SPM_BASE + 0xf14,
	SPM_SLEEP_CA15_WFI2_EN		= SPM_BASE + 0xf18,
	SPM_SLEEP_CA15_WFI3_EN		= SPM_BASE + 0xf1c,
};

enum {
	SPM_PROJECT_CODE	= 0xb16
};

enum {
	SPM_REGWR_EN		= 1U << 0,
	SPM_REGWR_CFG_KEY	= SPM_PROJECT_CODE << 16
};


/**************************************
 * Macro and Inline
 **************************************/
#define spm_read(addr)		read32((void *)(uintptr_t)(addr))
#define spm_write(addr, val)	write32((void *)(uintptr_t)(addr), (val))

#endif /* SOC_MEDIATEK_MT8173_SPM_H */
