/*
 * This file is part of the coreboot project.
 *
 * Copyright 2014 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 */

#ifndef SOC_MEDIATEK_MT8135_CUST_GPIO_BOOT_H
#define SOC_MEDIATEK_MT8135_CUST_GPIO_BOOT_H

#include <soc/gpio.h>
#include <soc/pinmux.h>

#define GPIO_CONFIGURATION(name, index, func, dir, pull_en, pull, val) \
	name##index##_MODE = func, \
	name##index##_DIR = dir, \
	name##index##_PULLEN = pull_en, \
	name##index##_PULL = pull, \
	name##index##_DATAOUT = val, \
	name##index##_DATAINV = GPIO_DATA_UNINV

#define GPIO_CFG(index, func, dir, pull_en, pull, val) \
	GPIO_CONFIGURATION(GPIO, index, func, dir, pull_en, pull, val)

#define GPIOEXT_CFG(index, func, dir, pull_en, pull, val) \
	GPIO_CONFIGURATION(GPIOEXT, index, func, dir, pull_en, pull, val)

enum {
	DIR_IN = GPIO_DIR_IN,
	DIR_OUT = GPIO_DIR_OUT,
	PULL_DIS = GPIO_PULL_DISABLE,
	PULL_ENA = GPIO_PULL_ENABLE,
	PULL_DN = GPIO_PULL_DOWN,
	PULL_UP = GPIO_PULL_UP,
	OUT_0 = GPIO_OUT_ZERO,
	OUT_1 = GPIO_OUT_ONE,

	GPIO_CFG(0, GPIO0_FUNC_MSDC0_DAT7, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(1, GPIO1_FUNC_MSDC0_DAT6, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(2, GPIO2_FUNC_MSDC0_DAT5, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(3, GPIO3_FUNC_MSDC0_DAT4, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(4, GPIO4_FUNC_MSDC0_CMD, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(5, GPIO5_FUNC_MSDC0_CLK, DIR_OUT, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(6, GPIO6_FUNC_MSDC0_DAT3, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(7, GPIO7_FUNC_MSDC0_DAT2, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(8, GPIO8_FUNC_MSDC0_DAT1, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(9, GPIO9_FUNC_MSDC0_DAT0, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	/* EC_IN_RW */
	GPIO_CFG(10, GPIO10_FUNC_GPIO10, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	/* EC_FW_UPDATE_L */
	GPIO_CFG(11, GPIO11_FUNC_GPIO11, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(12, GPIO12_FUNC_GPIO12, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(13, GPIO13_FUNC_GPIO13, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(14, GPIO14_FUNC_GPIO14, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(15, GPIO15_FUNC_GPIO15, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	/* AP_RESET */
	GPIO_CFG(16, GPIO16_FUNC_GPIO16, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(17, GPIO17_FUNC_GPIO17, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(18, GPIO18_FUNC_GPIO18, DIR_OUT, PULL_ENA, PULL_DN, OUT_1),
	GPIO_CFG(19, GPIO19_FUNC_GPIO19, DIR_OUT, PULL_ENA, PULL_DN, OUT_1),
	/* GL888S_CEN */
	GPIO_CFG(20, GPIO20_FUNC_GPIO20, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	/* GL888S_CB0_CTL */
	GPIO_CFG(21, GPIO21_FUNC_GPIO21, DIR_OUT, PULL_ENA, PULL_DN, OUT_0),
	/* GL888S_CB1_CTL */
	GPIO_CFG(22, GPIO22_FUNC_GPIO22, DIR_OUT, PULL_ENA, PULL_DN, OUT_0),
	/* PANEL_BL_ENABLE */
	GPIO_CFG(23, GPIO23_FUNC_GPIO23, DIR_OUT, PULL_ENA, PULL_UP, OUT_0),
	/* EC_INT */
	GPIO_CFG(24, GPIO24_FUNC_EINT153, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(25, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(26, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(27, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(28, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(29, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(30, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(31, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(32, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(33, GPIO33_FUNC_MSDC0_RSTB, DIR_OUT, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(34, GPIO34_FUNC_IDDIG, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(35, GPIO35_FUNC_SCL3, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(36, GPIO36_FUNC_SDA3, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(37, GPIO37_FUNC_AUD_CLK, DIR_OUT, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(38, GPIO38_FUNC_AUD_DAT_MOSI, DIR_OUT, PULL_ENA, PULL_DN,
		 OUT_0),
	GPIO_CFG(39, GPIO39_FUNC_AUD_DAT_MISO, DIR_IN, PULL_ENA, PULL_DN,
		 OUT_0),
	GPIO_CFG(40, GPIO40_FUNC_GPIO40, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(41, GPIO41_FUNC_GPIO41, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(42, GPIO42_FUNC_GPIO42, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(43, GPIO43_FUNC_PWRAP_SPIDI, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(44, GPIO44_FUNC_PWRAP_SPIDO, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(45, GPIO45_FUNC_PWRAP_SPICS_B_I, DIR_OUT, PULL_ENA, PULL_DN,
		 OUT_1),
	GPIO_CFG(46, GPIO46_FUNC_PWRAP_SPICK_I, DIR_OUT, PULL_ENA, PULL_DN,
		 OUT_0),
	GPIO_CFG(47, GPIO47_FUNC_PWRAP_EVENT_IN, DIR_IN, PULL_ENA, PULL_DN,
		 OUT_0),
	GPIO_CFG(48, GPIO48_FUNC_RTC32K_CK, DIR_IN, PULL_DIS, PULL_DN, OUT_0),
	GPIO_CFG(49, GPIO49_FUNC_WATCHDOG, DIR_OUT, PULL_DIS, PULL_DN, OUT_0),
	GPIO_CFG(50, GPIO50_FUNC_SRCLKENA, DIR_OUT, PULL_DIS, PULL_DN, OUT_1),
	GPIO_CFG(51, GPIO51_FUNC_SRCVOLTEN, DIR_OUT, PULL_DIS, PULL_DN, OUT_1),
	GPIO_CFG(52, GPIO52_FUNC_EINT0, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(53, GPIO53_FUNC_GPIO53, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(54, GPIO54_FUNC_GPIO54, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(55, GPIO55_FUNC_GPIO55, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(56, GPIO56_FUNC_GPIO56, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(57, GPIO57_FUNC_JTCK, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(58, GPIO58_FUNC_JTDO, DIR_IN, PULL_DIS, PULL_DN, OUT_1),
	GPIO_CFG(59, GPIO59_FUNC_JTRST_B, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(60, GPIO60_FUNC_JTDI, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(61, GPIO61_FUNC_JRTCK, DIR_IN, PULL_DIS, PULL_DN, OUT_0),
	GPIO_CFG(62, GPIO62_FUNC_JTMS, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(63, GPIO63_FUNC_MSDC1_INSI, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(64, GPIO64_FUNC_MSDC1_SDWPI, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	/* MSDC2_INSI */
	GPIO_CFG(65, GPIO65_FUNC_GPIO65, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	/* MSDC2_WP */
	GPIO_CFG(66, GPIO66_FUNC_GPIO66, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(67, GPIO67_FUNC_URXD4, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(68, GPIO68_FUNC_UTXD4, DIR_OUT, PULL_DIS, PULL_DN, OUT_1),
	GPIO_CFG(69, GPIO69_FUNC_URXD1, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(70, GPIO70_FUNC_UTXD1, DIR_OUT, PULL_DIS, PULL_DN, OUT_1),
	GPIO_CFG(71, GPIO71_FUNC_UCTS1, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(72, GPIO72_FUNC_URTS1, DIR_OUT, PULL_DIS, PULL_DN, OUT_1),
	GPIO_CFG(73, GPIO73_FUNC_GPIO73, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(74, GPIO74_FUNC_GPIO74, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(75, GPIO75_FUNC_EINT75, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(76, GPIO76_FUNC_GPIO76, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(77, GPIO77_FUNC_MSDC2_DAT2, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(78, GPIO78_FUNC_MSDC2_DAT3, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(79, GPIO79_FUNC_MSDC2_CMD, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(80, GPIO80_FUNC_MSDC2_CLK, DIR_OUT, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(81, GPIO81_FUNC_MSDC2_DAT1, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(82, GPIO82_FUNC_MSDC2_DAT0, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(83, GPIO83_FUNC_GPIO83, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(84, GPIO84_FUNC_GPIO84, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(85, GPIO85_FUNC_GPIO85, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(86, GPIO86_FUNC_GPIO86, DIR_OUT, PULL_ENA, PULL_UP, OUT_1),
	GPIO_CFG(87, GPIO87_FUNC_GPIO87, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(88, GPIO88_FUNC_GPIO88, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(89, GPIO89_FUNC_GPIO89, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(90, GPIO90_FUNC_GPIO90, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(91, GPIO91_FUNC_SPI1_CSN, DIR_OUT, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(92, GPIO92_FUNC_SPI1_MO, DIR_OUT, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(93, GPIO93_FUNC_SPI1_MI, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(94, GPIO94_FUNC_SPI1_CLK, DIR_OUT, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(95, GPIO95_FUNC_GPIO95, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(96, GPIO96_FUNC_GPIO96, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(97, GPIO97_FUNC_GPIO97, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(98, GPIO98_FUNC_GPIO98, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(99, GPIO99_FUNC_GPIO99, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(100, GPIO100_FUNC_SDA0, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(101, GPIO101_FUNC_SCL0, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(102, GPIO102_FUNC_EINT10, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	/* TPM RESET */
	GPIO_CFG(103, GPIO103_FUNC_GPIO103, DIR_OUT, PULL_ENA, PULL_UP, OUT_1),
	/* TPM INT */
	GPIO_CFG(104, GPIO104_FUNC_EINT16, DIR_IN, PULL_ENA, PULL_UP, OUT_1),
	GPIO_CFG(105, GPIO105_FUNC_I2SIN_CK, DIR_OUT, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(106, GPIO106_FUNC_I2SIN_WS, DIR_OUT, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(107, GPIO107_FUNC_I2SIN_DAT, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(108, GPIO108_FUNC_I2SOUT_DAT, DIR_OUT, PULL_ENA, PULL_DN,
		 OUT_0),
	GPIO_CFG(109, GPIO109_FUNC_EINT5, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(110, GPIO110_FUNC_GPIO110, DIR_OUT, PULL_DIS, PULL_DN, OUT_1),
	GPIO_CFG(111, GPIO111_FUNC_GPIO111, DIR_OUT, PULL_DIS, PULL_DN, OUT_0),
	GPIO_CFG(112, GPIO112_FUNC_EINT8, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(113, GPIO113_FUNC_EINT9, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	/* EC_LEVEL_SHIFT_EN */
	GPIO_CFG(114, GPIO114_FUNC_GPIO114, DIR_OUT, PULL_DIS, PULL_DN, OUT_1),
	GPIO_CFG(115, GPIO115_FUNC_GPIO115, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(116, GPIO116_FUNC_GPIO116, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(117, GPIO117_FUNC_EINT1, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(118, GPIO118_FUNC_GPIO118, DIR_OUT, PULL_ENA, PULL_DN, OUT_0),
	/* MT8135_EC_RESET */
	GPIO_CFG(119, GPIO119_FUNC_GPIO119, DIR_OUT, PULL_DIS, PULL_DN, OUT_0),
	GPIO_CFG(120, GPIO120_FUNC_EINT4, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(121, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(122, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(123, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(124, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(125, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(126, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(127, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(128, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(129, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(130, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(131, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(132, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(133, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(134, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(135, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(136, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(137, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(138, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(139, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(140, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(141, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(142, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(143, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(144, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(145, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(146, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(147, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(148, GPIO_MODE_00, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(149, GPIO149_FUNC_EINT36, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(150, GPIO150_FUNC_EINT35, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(151, GPIO151_FUNC_EINT169, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(152, GPIO152_FUNC_EINT168, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(153, GPIO153_FUNC_EINT163, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(154, GPIO154_FUNC_EINT162, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(155, GPIO155_FUNC_EINT167, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(156, GPIO156_FUNC_EINT166, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(157, GPIO157_FUNC_EINT165, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(158, GPIO158_FUNC_EINT164, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(159, GPIO159_FUNC_GPIO159, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(160, GPIO160_FUNC_GPIO160, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(161, GPIO161_FUNC_GPIO161, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(162, GPIO162_FUNC_GPIO162, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(163, GPIO163_FUNC_GPIO163, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(164, GPIO164_FUNC_GPIO164, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(165, GPIO165_FUNC_GPIO165, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(166, GPIO166_FUNC_GPIO166, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(167, GPIO167_FUNC_GPIO167, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(168, GPIO168_FUNC_GPIO168, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(169, GPIO169_FUNC_GPIO169, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(170, GPIO170_FUNC_GPIO170, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(171, GPIO171_FUNC_GPIO171, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(172, GPIO172_FUNC_GPIO172, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(173, GPIO173_FUNC_GPIO173, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(174, GPIO174_FUNC_GPIO174, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(175, GPIO175_FUNC_GPIO175, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(176, GPIO176_FUNC_GPIO176, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(177, GPIO177_FUNC_GPIO177, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(178, GPIO178_FUNC_GPIO178, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(179, GPIO179_FUNC_GPIO179, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(180, GPIO180_FUNC_GPIO180, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	/* HDMI_5V_FLT_N */
	GPIO_CFG(181, GPIO181_FUNC_GPIO181, DIR_IN, PULL_DIS, PULL_UP, OUT_0),
	/* HDMI_5V_EN */
	GPIO_CFG(182, GPIO182_FUNC_GPIO182, DIR_OUT, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(183, GPIO183_FUNC_GPIO183, DIR_OUT, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(184, GPIO184_FUNC_EINT184, DIR_OUT, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(185, GPIO185_FUNC_GPIO185, DIR_OUT, PULL_ENA, PULL_UP, OUT_0),
	GPIO_CFG(186, GPIO186_FUNC_GPIO186, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(187, GPIO187_FUNC_GPIO187, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(188, GPIO188_FUNC_GPIO188, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(189, GPIO189_FUNC_GPIO189, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(190, GPIO190_FUNC_GPIO190, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(191, GPIO191_FUNC_GPIO191, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(192, GPIO192_FUNC_GPIO192, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(193, GPIO193_FUNC_SDA2, DIR_IN, PULL_DIS, PULL_DN, OUT_0),
	GPIO_CFG(194, GPIO194_FUNC_SCL2, DIR_IN, PULL_DIS, PULL_DN, OUT_0),
	GPIO_CFG(195, GPIO195_FUNC_SDA1, DIR_IN, PULL_DIS, PULL_DN, OUT_0),
	GPIO_CFG(196, GPIO196_FUNC_SCL1, DIR_IN, PULL_DIS, PULL_DN, OUT_0),
	GPIO_CFG(197, GPIO197_FUNC_GPIO197, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(198, GPIO198_FUNC_GPIO198, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(199, GPIO199_FUNC_GPIO199, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(200, GPIO200_FUNC_GPIO200, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(201, GPIO201_FUNC_GPIO201, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIO_CFG(202, GPIO202_FUNC_GPIO202, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIOEXT_CFG(0, GPIOEXT0_FUNC_INT, DIR_OUT, PULL_DIS, PULL_DN, OUT_0),
	GPIOEXT_CFG(1, GPIOEXT1_FUNC_SRCVOLTEN, DIR_IN, PULL_ENA, PULL_UP,
		    OUT_0),
	GPIOEXT_CFG(2, GPIOEXT2_FUNC_SRCLKEN_PERI, DIR_IN, PULL_ENA, PULL_UP,
		    OUT_0),
	GPIOEXT_CFG(3, GPIOEXT3_FUNC_RTC_32K1V8, DIR_IN, PULL_DIS, PULL_DN,
		    OUT_0),
	GPIOEXT_CFG(4, GPIOEXT4_FUNC_WRAP_EVENT, DIR_OUT, PULL_DIS, PULL_DN,
		    OUT_0),
	GPIOEXT_CFG(5, GPIOEXT5_FUNC_SPI_CLK, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIOEXT_CFG(6, GPIOEXT6_FUNC_SPI_CSN, DIR_IN, PULL_ENA, PULL_DN, OUT_0),
	GPIOEXT_CFG(7, GPIOEXT7_FUNC_SPI_MOSI, DIR_IN, PULL_ENA, PULL_DN,
		    OUT_0),
	GPIOEXT_CFG(8, GPIOEXT8_FUNC_SPI_MISO, DIR_IN, PULL_ENA, PULL_DN,
		    OUT_0),
	GPIOEXT_CFG(9, GPIOEXT9_FUNC_AUD_CLK, DIR_IN, PULL_DIS, PULL_DN, OUT_0),
	GPIOEXT_CFG(10, GPIOEXT10_FUNC_AUD_MISO, DIR_OUT, PULL_ENA, PULL_DN,
		    OUT_0),
	GPIOEXT_CFG(11, GPIOEXT11_FUNC_AUD_MOSI, DIR_IN, PULL_ENA, PULL_DN,
		    OUT_0),
	GPIOEXT_CFG(12, GPIOEXT12_FUNC_COL0_USBDL, DIR_IN, PULL_ENA, PULL_UP,
		    OUT_0),
	/* CURRENT_LIMIT_ALERT_N */
	GPIOEXT_CFG(13, GPIOEXT13_FUNC_EINT11_1X, DIR_IN, PULL_ENA, PULL_UP,
		    OUT_1),
	/* THERM_LEVEL_EN */
	GPIOEXT_CFG(14, GPIOEXT14_FUNC_GPIO14, DIR_OUT, PULL_ENA, PULL_DN,
		    OUT_1),
	/* THERM_ALERT_N */
	GPIOEXT_CFG(15, GPIOEXT15_FUNC_GPIO15, DIR_IN, PULL_ENA, PULL_UP,
		    OUT_0),
	/* THERM_OVERT_N */
	GPIOEXT_CFG(16, GPIOEXT16_FUNC_GPIO16, DIR_OUT, PULL_DIS, PULL_UP,
		    OUT_0),
	/* USPEND_L_1V8	*/
	GPIOEXT_CFG(17, GPIOEXT17_FUNC_GPIO17, DIR_OUT, PULL_DIS, PULL_DN,
		    OUT_1),
	/* CURRENT_LIMIT_EN */
	GPIOEXT_CFG(18, GPIOEXT18_FUNC_GPIO18, DIR_OUT, PULL_ENA, PULL_UP,
		    OUT_1),
	/* ARM_RESET_1V8 */
	GPIOEXT_CFG(19, GPIOEXT19_FUNC_GPIO19, DIR_IN, PULL_ENA, PULL_DN,
		    OUT_0),
	GPIOEXT_CFG(20, GPIOEXT20_FUNC_ROW0, DIR_OUT, PULL_DIS, PULL_DN, OUT_0),
	/* C_BL_OVERRIDE_1V8 */
	GPIOEXT_CFG(21, GPIOEXT21_FUNC_GPIO21, DIR_IN, PULL_ENA, PULL_DN,
		    OUT_0),
	/* USB2_ILIM_SEL */
	GPIOEXT_CFG(22, GPIOEXT22_FUNC_GPIO22, DIR_OUT, PULL_DIS, PULL_UP,
		    OUT_0),
	/* USB2_PWR_EN */
	GPIOEXT_CFG(23, GPIOEXT23_FUNC_GPIO23, DIR_OUT, PULL_ENA, PULL_UP,
		    OUT_0),
	/* USB_CTL1 */
	GPIOEXT_CFG(24, GPIOEXT24_FUNC_GPIO24, DIR_OUT, PULL_DIS, PULL_UP,
		    OUT_0),
	/* USB2_STATUS_L Input, active low */
	GPIOEXT_CFG(25, GPIOEXT25_FUNC_GPIO25, DIR_IN, PULL_DIS, PULL_DN,
		    OUT_1),
	/* USB_OC1_N EINT, active low */
	GPIOEXT_CFG(26, GPIOEXT26_FUNC_EINT24_1X, DIR_IN, PULL_ENA, PULL_UP,
		    OUT_1),
	GPIOEXT_CFG(27, GPIOEXT27_FUNC_GPIO27, DIR_IN, PULL_ENA, PULL_DN,
		    OUT_0),
	GPIOEXT_CFG(28, GPIOEXT28_FUNC_GPIO28, DIR_IN, PULL_ENA, PULL_DN,
		    OUT_0),
	GPIOEXT_CFG(29, GPIOEXT29_FUNC_GPIO29, DIR_IN, PULL_ENA, PULL_DN,
		    OUT_0),
	GPIOEXT_CFG(30, GPIOEXT30_FUNC_GPIO30, DIR_IN, PULL_ENA, PULL_DN,
		    OUT_0),
	GPIOEXT_CFG(31, GPIOEXT31_FUNC_SCL0, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIOEXT_CFG(32, GPIOEXT32_FUNC_SDA0, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIOEXT_CFG(33, GPIOEXT33_FUNC_SCL1, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIOEXT_CFG(34, GPIOEXT34_FUNC_SDA1, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIOEXT_CFG(35, GPIOEXT35_FUNC_SCL2, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIOEXT_CFG(36, GPIOEXT36_FUNC_SDA2, DIR_IN, PULL_ENA, PULL_UP, OUT_0),
	GPIOEXT_CFG(37, GPIOEXT37_FUNC_HDMISD, DIR_IN, PULL_DIS, PULL_DN,
		    OUT_0),
	GPIOEXT_CFG(38, GPIOEXT38_FUNC_HDMISCK, DIR_IN, PULL_DIS, PULL_DN,
		    OUT_0),
	GPIOEXT_CFG(39, GPIOEXT39_FUNC_HTPLG, DIR_IN, PULL_DIS, PULL_DN, OUT_0),
	GPIOEXT_CFG(40, GPIOEXT40_FUNC_CEC, DIR_IN, PULL_DIS, PULL_DN, OUT_0),
};

#endif /* SOC_MEDIATEK_MT8135_CUST_GPIO_BOOT_H */
